on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build Docker image
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          service_account: 'cloud-run-deployer@notely-465521.iam.gserviceaccount.com'

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notely-465521

      - name: gcloud check
        run: gcloud info

      - name: Upload image to cloud
        run: gcloud builds submit --service_account=cloud-run-deployer@notely-465521.iam.gserviceaccount.com --tag us-west1-docker.pkg.dev/notely-465521/notely-ar-repo/notely:latest .
