on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build Docker image
        run: ./scripts/buildprod.sh

      - name: Set GCP Project
        run: gcloud config set project notely-465521

      - name: Upload image to cloud
        run: gcloud builds submit --tag us-west1-docker.pkg.dev/notely-465521/notely-ar-repo/notely:latest .
